DROP TABLE IF EXISTS clients;
CREATE TABLE clients (
    uuid int DEFAULT 0 NOT NULL,
    first_name text NULL,
    middle_name date NULL,
    last_name text NULL,
    name_data_quality text NULL,
    ssn int NULL,
    ssn_data_quality int NULL,
    dob date NULL,
    AmIndAKNative int NULL,
    Asian int NULL,
    Black int NULL,
    NativeHIOtherPacific int NULL,
    White int NULL,
    RaceNone int NULL,
    Gender int NULL,
    OtherGender int NULL,
    veteran_status int NULL,
    year_entered_service int NULL,
    year_separated int NULL,
    WorldWarII int NULL,
    KoreanWar int NULL,
    VietnamWar int NULL,
    DesertStorm int NULL,
    AfghanistanOEF int NULL,
    IraqOIF int NULL,
    IraqOND int NULL,
    OtherTheater int NULL,
    MilitaryBranch int NULL,
    Discharge_Status int NULL,
    date_created date NULL,
    date_updated date NULL,
    user_id int NULL
);

DROP TABLE IF EXISTS disabilities;
CREATE TABLE disabilities (
    disabilities_id int NOT NULL,
    project_entry_id int NULL,
    personal_id int NULL,
	information_date date NULL,
	disabilitiy_type int NULL,
	disability_response int NULL,
	indefinite_and_impairs int NULL,
	documentation_on_file int NULL,
	receiving_services int NULL,
	PATH_how_confirmed int NULL,
	PATH_SMI_information int NULL,
	tcell_count_available int NULL,
	tcell_count int NULL,
	tcell_source int NULL,
	viral_load_available int NULL,
	viral_load int NULL,
	viral_load_source int NULL,
	data_collection_stage int NULL,
	date_created date NULL,
	date_updated date NULL,
	user_id int NULL,
	date_deleted date NULL,
	export_id int NULL
);

DROP TABLE IF EXISTS employment_education;
CREATE TABLE employment_education (
    employment_education_id int NOT NULL,
    project_entry_id int NOT NULL,
    personal_id int NOT NULL,
	information_date date NOT NULL,
	last_grade_completed int NULL,
	school_status int NULL,
	employed int NULL,
	employment_type int NULL,
	not_employed_reason int NULL,
	data_collection_stage int NULL,
	date_created date NULL,
	date_updated date NULL,
	user_id int NULL,
	date_deleted date NULL,
	export_id int NULL
);

DROP TABLE IF EXISTS enrollment;
CREATE TABLE enrollment (
    project_entry_id int NOT NULL,
    personal_id int NOT NULL,
    project_id int NOT NULL,
	entry_date date NULL,
	household_id int NULL,
	relationship_to_hoh int NULL,
	residence_prior int NULL,
	other_residence_prior int NULL,
	residence_prior_length_of_stay int NULL,
	disabling_condition int NULL,
	entry_from_street_essh int NULL,
	date_to_street_essh date NULL,
	times_homless_past_three_years int NULL,
	months_homeless_past_three_years int NULL,
	housing_status int NULL,
	date_of_engagement date NULL,
	in_permanent_housing int NULL,
	residential_move_in_date date NULL,
	date_of_PATH_status date NULL,
	client_enrolled_in_PATH int NULL,
	reason_not_enrolled int NULL,
	worst_housing_situation int NULL,
	percent_AMI int NULL,
	last_permanent_street text NULL,
	last_permanent_city text NULL,
	last_permanent_state text NULL,
	last_permanent_zip text NULL,
	address_data_quality int NULL,
	date_of_bcp_status int NULL,
	fysb_youth int NULL,
	reason_no_servies int NULL,
	sexual_orientation int NULL,
	former_ward_child_welfare int NULL,
	child_welfare_years int NULL,
	child_welfare_months int NULL,
	former_ward_juvenile_justice int NULL,
	juvenile_justice_years int NULL,
	household_dynamics int NULL,
	sexual_orientation_gender_id_youth int NULL,
	sexual_orientation_gender_id_fam int NULL,
	housing_issues_youth int NULL,
	housing_issues_fam int NULL,
	school_educational_issues_youth int NULL,
	school_education_issues_fam int NULL,
	unemployment_youth int NULL,
	unemployment_fam int NULL,
	mental_health_issues_youth int NULL,
	mental_health_issues_fam int NULL,
	health_issues_youth int NULL,
	health_issues_fam int NULL,
	physical_disability_youth int NULL,
	physical_disability_fam int NULL,
	mental_disability_youth int NULL,
	mental_disability_fam int NULL,
	abuse_and_neglect_youth int NULL,
	abuse_and_neglect_fam int NULL,
	alcohol_drug_abuse_youth int NULL,
	alcohol_drug_abuse_fam int NULL,
	insufficient_income int NULL,
	active_military_parent int NULL,
	incarcerated_parent int NULL,
	incarcerated_parent_status int NULL,
	referral_source int NULL,
	court_ourtreach_referral_approaches int NULL,
	exchange_for_sex int NULL,
	exchange_for_sex_past_three_months int NULL,
	count_of_exchanges_for_sex int NULL,
	asked_or_forced_to_exchange_for_sex int NULL,
	asked_or_forced_to_exchange_for_sex_past_three_months int NULL,
	workplace_violence_threats int NULL,
	workplace_promise_difference int NULL,
	coerced_to_continue_work int NULL,
	labor_exploit_past_three_months int NULL,
	hp_screening_score int NULL,
	vamc_station int NULL,
	date_created date NULL,
	date_updated date NULL,
	user_id int NULL,
	date_deleted date NULL,
	export_id int NULL
);

DROP TABLE IF EXISTS exit;
CREATE TABLE exit (
    exit_id int NOT NULL,
    project_entry_id int NOT NULL,
    personal_id int NOT NULL,
	exit_date date NOT NULL,
	destination int NULL,
	other_destination int NULL,
	assessment_disposition int NULL,
	other_disposition int NULL,
	housing_assignment int NULL,
	subsity_information int NULL,
	connection_with_soar int NULL,
	written_aftercare_plan int NULL,
	assistance_mainstream_benefits int NULL,
	permanent_housing_placement int NULL,
	temporary_shelter_placement int NULL,
	exit_counseling int NULL,
	further_follow_up_services int NULL,
	scheduled_follow_up_contacts int NULL,
	resource_package int NULL,
	other_aftercare_plan_or_action int NULL,
	project_completion_status int NULL,
	early_exit_reason int NULL,
	family_reunification_achieved int NULL,
	date_created date NULL,
	date_updated date NULL,
	user_id int NULL,
	date_deleted date NULL,
	export_id int NULL
);


DROP TABLE IF EXISTS funder;
CREATE TABLE funder (
    funder_id integer NULL,
    project_id integer NULL,
    funder integer NULL,
    grant_id integer NULL,
    start_date TIMESTAMP NULL,
    end_date TIMESTAMP NULL,
    date_created TIMESTAMP NOT NULL,
    date_updated TIMESTAMP NOT NULL,
    user_id integer NULL,
    date_deleted TIMESTAMP NULL,
    export_id integer NULL
);

DROP TABLE IF EXISTS health_and_dvid;
CREATE TABLE health_and_dvid (
    health_and_dvid integer NULL,
    project_entry_id integer NULL,
    personal_id integer NULL,
    information_date TIMESTAMP NULL,
    domestic_violence_victim integer NULL,
    when_occurred integer NULL,
    currently_fleeing integer NULL,
    general_health_status integer NULL,
    dental_health_status integer NULL,
    mental_health_status integer NULL,
    pregnancy_status integer NULL,
    due_date TIMESTAMP NULL,
    data_collection_stage integer NULL,
    date_created TIMESTAMP NOT NULL,
    date_updated TIMESTAMP NOT NULL,
    user_id integer NULL,
    date_deleted TIMESTAMP NULL,
    export_id integer NULL
);

DROP TABLE IF EXISTS income_benefits;
CREATE TABLE income_benefits (
    income_benefits_id integer NULL,
    project_entry_id integer NULL,
    personal_id integer NULL,
    information_date TIMESTAMP NULL,
    income_from_any_source integer NULL,
    total_monthly_income REPLACE_MONEY NULL,
    earned integer NULL,
    earned_amount REPLACE_MONEY NULL,
    unemployment integer NULL,
    unemployment_amount REPLACE_MONEY NULL,
    ssi integer NULL,
    ssi_amount REPLACE_MONEY NULL,
    ssdi integer NULL,
    ssdi_amount REPLACE_MONEY NULL,
    va_disability_service integer NULL,
    va_disability_service_amount REPLACE_MONEY NULL,
    va_disability_non_service integer NULL,
    va_disability_non_service_amount REPLACE_MONEY NULL,
    private_disability integer NULL,
    private_disability_amount REPLACE_MONEY NULL,
    workers_comp integer NULL,
    workers_comp_amount REPLACE_MONEY NULL,
    tanf integer NULL,
    tanf_amount REPLACE_MONEY NULL,
    ga integer NULL,
    ga_amount REPLACE_MONEY NULL,
    soc_sec_retirement integer NULL,
    soc_sec_retirement_amount REPLACE_MONEY NULL,
    pension integer NULL,
    pension_amount REPLACE_MONEY NULL,
    child_support integer NULL,
    child_support_amount REPLACE_MONEY NULL,
    alimony integer NULL,
    alimony_amount REPLACE_MONEY NULL,
    other_income_source integer NULL,
    other_income_amount REPLACE_MONEY NULL,
    other_income_source_identify text NULL,
    benefits_from_any_source integer NULL,
    snap integer NULL,
    wic integer NULL,
    tanf_child_care integer NULL,
    tanf_transportation integer NULL,
    other_tanf integer NULL,
    rental_assistance_ongoing integer NULL,
    rental_assistance_temp integer NULL,
    other_benefits_source integer NULL,
    other_benefits_source_identify text NULL,
    insurance_from_any_source integer NULL,
    medicaid integer NULL,
    no_medicaid_reason text NULL,
    medicare integer NULL,
    no_medicare_reason text NULL,
    schip integer NULL,
    no_schip_reason text NULL,
    va_medical_services integer NULL,
    no_va_med_reason text NULL,
    employer_provided integer NULL,
    no_employer_provided_reason text NULL,
    cobra integer NULL,
    no_cobra_reason text NULL,
    private_pay integer NULL,
    no_private_pay_reason text NULL,
    state_health_ins integer NULL,
    no_state_health_ins_reason text NULL,
    hivaids_assistance integer NULL,
    no_hivaids_assistance_reason text NULL,
    adap integer NULL,
    no_adap_reason text NULL,
    data_collection_stage,
    date_created TIMESTAMP NOT NULL,
    date_updated TIMESTAMP NOT NULL,
    user_id integer NULL,
    date_deleted TIMESTAMP NULL,
    export_id integer NULL
);

DROP TABLE IF EXISTS services;
CREATE TABLE services (
    services_id integer NULL,
    project_entry_id integer NULL,
    personal_id integer NULL,
    date_provided TIMESTAMP NULL,
    record_type integer NULL,
    type_provided integer NULL,
    other_type_provided integer NULL,
    sub_type_provided integer NULL,
    fa_amount integer NULL,
    referral_outcome integer NULL,
    date_created TIMESTAMP NOT NULL,
    date_updated TIMESTAMP NOT NULL,
    user_id integer NULL,
    date_deleted TIMESTAMP NULL,
    export_id integer NULL
);
